-- Seed 80 AI agents to reach 200 total
-- Focus on: Coding, Writing, Image, Video, Voice, Automation, Frameworks

-- Ensure categories exist
INSERT INTO public.categories (name, icon) VALUES
('Coding Assistants', '💻'),
('Writing Tools', '✍️'),
('Image Generation', '🎨'),
('Video Generation', '🎬'),
('Voice AI', '🎤'),
('Workflow Automation', '⚡'),
('AI Frameworks', '🏗️'),
('Data Analysis', '📊'),
('Design Tools', '🎨'),
('Music & Audio', '🎵'),
('3D & Gaming', '🎮'),
('Productivity', '⚙️'),
('Marketing', '📢')
ON CONFLICT (name) DO NOTHING;

-- Insert 80 AI agents
INSERT INTO public.products (
  codename,
  punchline,
  description,
  product_website,
  categories,
  tags,
  labels,
  user_id,
  approved,
  featured,
  logo_src
) VALUES

-- CODING ASSISTANTS (15 agents)
(
  'devin',
  'The first AI software engineer',
  'Devin is an autonomous AI software engineer that can plan, code, debug, and deploy entire projects. It can work alongside human developers, handle complex tasks, and even train its own AI models.',
  'https://www.cognition-labs.com/devin',
  'Coding Assistants',
  ARRAY['Code Generation', 'Autonomous', 'Full-Stack', 'Testing', 'Deployment'],
  ARRAY['Paid', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.cognition-labs.com/favicon.ico'
),
(
  'github-copilot',
  'Your AI pair programmer',
  'GitHub Copilot suggests code completions as you type. Powered by OpenAI Codex, it understands context from your code and comments to generate entire functions, tests, and more.',
  'https://github.com/features/copilot',
  'Coding Assistants',
  ARRAY['Code Completion', 'Code Generation', 'IDE Integration', 'Testing'],
  ARRAY['Paid', 'VS Code', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'codeium',
  'Free AI-powered code acceleration',
  'Codeium offers AI-powered autocomplete, natural language search, and chat for 70+ programming languages. Free for individual developers with enterprise options.',
  'https://codeium.com',
  'Coding Assistants',
  ARRAY['Code Completion', 'Code Generation', 'IDE Integration'],
  ARRAY['Freemium', 'VS Code', 'Browser Extension'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://codeium.com/favicon.ico'
),
(
  'tabnine',
  'AI assistant for software developers',
  'Tabnine is a privacy-first AI code assistant that runs on your local machine or private cloud. Supports all major IDEs and programming languages.',
  'https://www.tabnine.com',
  'Coding Assistants',
  ARRAY['Code Completion', 'Privacy', 'Local LLMs', 'IDE Integration'],
  ARRAY['Freemium', 'Self-Hosted', 'VS Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.tabnine.com/favicon.ico'
),
(
  'replit-ghostwriter',
  'AI pair programmer in the browser',
  'Replit Ghostwriter is an AI assistant built into Replit''s browser IDE. Offers code completion, generation, explanation, and debugging help.',
  'https://replit.com/ai',
  'Coding Assistants',
  ARRAY['Code Completion', 'Code Generation', 'Web App', 'Debugging'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://replit.com/favicon.ico'
),
(
  'sourcegraph-cody',
  'AI coding assistant with codebase context',
  'Cody uses your entire codebase as context to write, fix, and understand code. Integrates with VS Code, JetBrains, and other IDEs.',
  'https://sourcegraph.com/cody',
  'Coding Assistants',
  ARRAY['Code Generation', 'Context Management', 'Refactoring', 'IDE Integration'],
  ARRAY['Freemium', 'VS Code', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://sourcegraph.com/favicon.ico'
),
(
  'aider',
  'AI pair programming in your terminal',
  'Aider is a CLI tool that lets you pair program with AI. It can edit multiple files, use git, write tests, and refactor code with GPT-4 or Claude.',
  'https://github.com/paul-gauthier/aider',
  'Coding Assistants',
  ARRAY['Code Generation', 'Refactoring', 'Git Integration', 'Terminal'],
  ARRAY['Open Source', 'Free', 'CLI'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'continue-dev',
  'Open-source AI code assistant',
  'Continue is an open-source autopilot for VS Code. Chat, edit, and generate code with any LLM including GPT-4, Claude, and local models.',
  'https://continue.dev',
  'Coding Assistants',
  ARRAY['Code Generation', 'Open Source', 'Local LLMs', 'IDE Integration'],
  ARRAY['Open Source', 'Free', 'VS Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://continue.dev/favicon.ico'
),
(
  'aws-codewhisperer',
  'Amazon''s AI coding companion',
  'CodeWhisperer generates code suggestions based on your comments and existing code. Free for individual developers with AWS integration.',
  'https://aws.amazon.com/codewhisperer/',
  'Coding Assistants',
  ARRAY['Code Completion', 'Code Generation', 'AWS', 'Security'],
  ARRAY['Freemium', 'VS Code', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://aws.amazon.com/favicon.ico'
),
(
  'phind',
  'AI search engine for developers',
  'Phind is a search engine optimized for developers. Get instant answers to technical questions with AI-powered explanations and code examples.',
  'https://www.phind.com',
  'Coding Assistants',
  ARRAY['Code Search', 'Documentation', 'Learning', 'Web App'],
  ARRAY['Free', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.phind.com/favicon.ico'
),
(
  'warp-ai',
  'The terminal reimagined with AI',
  'Warp is a modern terminal with built-in AI command search, suggestions, and explanations. Makes terminal commands discoverable and understandable.',
  'https://www.warp.dev',
  'Coding Assistants',
  ARRAY['Terminal', 'Command Line', 'Productivity', 'Documentation'],
  ARRAY['Freemium', 'Desktop App', 'CLI'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.warp.dev/favicon.ico'
),
(
  'bito-ai',
  'AI assistant for developers',
  'Bito generates code, writes tests, explains code, and improves performance. Supports 50+ IDEs and works with your existing codebase.',
  'https://bito.ai',
  'Coding Assistants',
  ARRAY['Code Generation', 'Testing', 'Code Review', 'IDE Integration'],
  ARRAY['Freemium', 'VS Code', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://bito.ai/favicon.ico'
),
(
  'blackbox-ai',
  'AI-powered coding assistant',
  'Blackbox AI offers code autocomplete, chat, and code search. Extract code from videos, turn designs into code, and more.',
  'https://www.blackbox.ai',
  'Coding Assistants',
  ARRAY['Code Generation', 'Code Completion', 'Design to Code'],
  ARRAY['Freemium', 'VS Code', 'Browser Extension'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.blackbox.ai/favicon.ico'
),
(
  'codegen',
  'Salesforce''s open-source code model',
  'CodeGen is an open-source family of autoregressive models for program synthesis. Available in multiple sizes from 350M to 16B parameters.',
  'https://github.com/salesforce/CodeGen',
  'Coding Assistants',
  ARRAY['Code Generation', 'Open Source', 'Local LLMs', 'Research'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'codium-ai',
  'Automated test generation for code review',
  'CodiumAI generates meaningful tests for your code, analyzes code behavior, and suggests improvements. Integrates with your IDE.',
  'https://www.codium.ai',
  'Coding Assistants',
  ARRAY['Testing', 'Code Review', 'Code Analysis', 'IDE Integration'],
  ARRAY['Freemium', 'VS Code', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.codium.ai/favicon.ico'
),

-- AI FRAMEWORKS (10 agents)
(
  'langchain',
  'Framework for building LLM applications',
  'LangChain is the most popular framework for developing applications powered by language models. Provides tools for chains, agents, memory, and more.',
  'https://langchain.com',
  'AI Frameworks',
  ARRAY['Framework', 'LLM', 'Open Source', 'Python', 'JavaScript'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://langchain.com/favicon.ico'
),
(
  'crewai',
  'Framework for orchestrating role-playing AI agents',
  'CrewAI enables you to create AI agents that work together as a crew. Each agent has a role, goal, and backstory, collaborating to complete complex tasks.',
  'https://www.crewai.com',
  'AI Frameworks',
  ARRAY['Multi-Agent', 'Framework', 'Python', 'Orchestration', 'Open Source'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.crewai.com/favicon.ico'
),
(
  'autogen',
  'Microsoft''s multi-agent conversation framework',
  'AutoGen enables building LLM applications using multiple agents that can converse with each other to solve tasks. Supports complex workflows and human-in-the-loop.',
  'https://microsoft.github.io/autogen/',
  'AI Frameworks',
  ARRAY['Multi-Agent', 'Framework', 'Python', 'Microsoft', 'Open Source'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'llamaindex',
  'Data framework for LLM applications',
  'LlamaIndex (formerly GPT Index) provides tools to connect custom data sources to LLMs. Build RAG applications, chatbots, and more.',
  'https://www.llamaindex.ai',
  'AI Frameworks',
  ARRAY['Framework', 'RAG', 'Data', 'Open Source', 'Python'],
  ARRAY['Open Source', 'Free', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.llamaindex.ai/favicon.ico'
),
(
  'haystack',
  'End-to-end NLP framework',
  'Haystack is an open-source NLP framework for building production-ready search, question answering, and LLM applications.',
  'https://haystack.deepset.ai',
  'AI Frameworks',
  ARRAY['Framework', 'NLP', 'Search', 'RAG', 'Open Source'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://haystack.deepset.ai/favicon.ico'
),
(
  'semantic-kernel',
  'Microsoft''s SDK for AI orchestration',
  'Semantic Kernel is an SDK that integrates LLMs like OpenAI, Azure OpenAI, and Hugging Face with conventional programming languages.',
  'https://github.com/microsoft/semantic-kernel',
  'AI Frameworks',
  ARRAY['Framework', 'SDK', 'Microsoft', 'C#', '.NET', 'Python'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'langsmith',
  'Platform for debugging and testing LLM applications',
  'LangSmith helps developers debug, test, evaluate, and monitor LLM applications. Built by the LangChain team.',
  'https://smith.langchain.com',
  'AI Frameworks',
  ARRAY['Testing', 'Monitoring', 'Debugging', 'LLM', 'DevOps'],
  ARRAY['Freemium', 'Cloud', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://smith.langchain.com/favicon.ico'
),
(
  'dspy',
  'Programming framework for foundation models',
  'DSPy is a framework for algorithmically optimizing LM prompts and weights. Replaces fragile prompt engineering with programming.',
  'https://github.com/stanfordnlp/dspy',
  'AI Frameworks',
  ARRAY['Framework', 'Prompt Engineering', 'Optimization', 'Research'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'agentops',
  'Observability platform for AI agents',
  'AgentOps provides monitoring, debugging, and analytics for AI agents. Track agent behavior, costs, and performance in production.',
  'https://www.agentops.ai',
  'AI Frameworks',
  ARRAY['Monitoring', 'Observability', 'Analytics', 'DevOps'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.agentops.ai/favicon.ico'
),
(
  'superagent',
  'Open-source AI assistant framework',
  'Superagent is an open-source framework for building, deploying, and managing LLM-powered agents. Includes agent memory, tools, and workflows.',
  'https://www.superagent.sh',
  'AI Frameworks',
  ARRAY['Framework', 'Multi-Agent', 'Open Source', 'Deployment'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.superagent.sh/favicon.ico'
),

-- WRITING TOOLS (10 agents)
(
  'jasper',
  'AI content platform for marketing teams',
  'Jasper helps marketing teams create high-quality content faster. Generate blog posts, ads, emails, and more with brand voice consistency.',
  'https://www.jasper.ai',
  'Writing Tools',
  ARRAY['Content Creation', 'Marketing', 'Copywriting', 'Brand Voice'],
  ARRAY['Paid', 'Cloud', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.jasper.ai/favicon.ico'
),
(
  'copy-ai',
  'AI marketing copy and content',
  'Copy.ai helps you write marketing copy, product descriptions, social media posts, and more. Supports 25+ languages.',
  'https://www.copy.ai',
  'Writing Tools',
  ARRAY['Copywriting', 'Marketing', 'Social Media', 'Multilingual'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.copy.ai/favicon.ico'
),
(
  'writesonic',
  'AI writer for articles, blog posts & more',
  'Writesonic generates SEO-optimized content, blog posts, landing pages, and ads. Includes AI article writer and Chatsonic AI assistant.',
  'https://writesonic.com',
  'Writing Tools',
  ARRAY['Content Creation', 'SEO', 'Blog Writing', 'Marketing'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://writesonic.com/favicon.ico'
),
(
  'rytr',
  'AI writing assistant for fast content creation',
  'Rytr generates high-quality content in seconds. Create blog posts, emails, ads, and more in 30+ languages and 20+ tones.',
  'https://rytr.me',
  'Writing Tools',
  ARRAY['Content Creation', 'Copywriting', 'Multilingual', 'Email'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://rytr.me/favicon.ico'
),
(
  'notion-ai',
  'AI writing assistant in Notion',
  'Notion AI helps you write, brainstorm, edit, summarize, and translate directly in your Notion workspace.',
  'https://www.notion.so/product/ai',
  'Writing Tools',
  ARRAY['Content Creation', 'Note Taking', 'Productivity', 'Summarization'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.notion.so/favicon.ico'
),
(
  'sudowrite',
  'AI writing partner for fiction authors',
  'Sudowrite helps fiction writers brainstorm, develop characters, write scenes, and overcome writer''s block with AI.',
  'https://www.sudowrite.com',
  'Writing Tools',
  ARRAY['Creative Writing', 'Fiction', 'Storytelling', 'Brainstorming'],
  ARRAY['Paid', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.sudowrite.com/favicon.ico'
),
(
  'grammarly',
  'AI-powered writing assistant',
  'Grammarly checks grammar, spelling, punctuation, and style. Offers suggestions to improve clarity, engagement, and tone.',
  'https://www.grammarly.com',
  'Writing Tools',
  ARRAY['Grammar', 'Editing', 'Proofreading', 'Style'],
  ARRAY['Freemium', 'Browser Extension', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.grammarly.com/favicon.ico'
),
(
  'quillbot',
  'AI paraphrasing and summarization tool',
  'QuillBot rephrases text to improve clarity, strengthen vocabulary, and avoid plagiarism. Includes summarizer, grammar checker, and more.',
  'https://quillbot.com',
  'Writing Tools',
  ARRAY['Paraphrasing', 'Summarization', 'Grammar', 'Research'],
  ARRAY['Freemium', 'Web App', 'Browser Extension'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://quillbot.com/favicon.ico'
),
(
  'wordtune',
  'AI writing companion',
  'Wordtune helps you rewrite and rephrase sentences for clarity and impact. Suggests alternative ways to express your ideas.',
  'https://www.wordtune.com',
  'Writing Tools',
  ARRAY['Rewriting', 'Editing', 'Paraphrasing', 'Tone'],
  ARRAY['Freemium', 'Browser Extension', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.wordtune.com/favicon.ico'
),
(
  'simplified',
  'All-in-one AI content creation platform',
  'Simplified offers AI writing, design, video editing, and social media management in one platform. Perfect for marketing teams.',
  'https://simplified.com',
  'Writing Tools',
  ARRAY['Content Creation', 'Marketing', 'Design', 'Social Media'],
  ARRAY['Freemium', 'Cloud', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://simplified.com/favicon.ico'
),

-- IMAGE GENERATION (10 agents)
(
  'midjourney',
  'AI art generation from text',
  'Midjourney creates stunning images from text prompts. Accessed through Discord, it''s known for artistic, high-quality outputs.',
  'https://www.midjourney.com',
  'Image Generation',
  ARRAY['Text to Image', 'Art', 'Discord', 'Creative'],
  ARRAY['Paid', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.midjourney.com/favicon.ico'
),
(
  'dall-e-3',
  'OpenAI''s advanced image generator',
  'DALL-E 3 generates highly detailed images from text descriptions. Integrated with ChatGPT Plus for easy access.',
  'https://openai.com/dall-e-3',
  'Image Generation',
  ARRAY['Text to Image', 'OpenAI', 'High Quality', 'Creative'],
  ARRAY['Paid', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://openai.com/favicon.ico'
),
(
  'stable-diffusion',
  'Open-source image generation',
  'Stable Diffusion is an open-source text-to-image model that can run on consumer hardware. Highly customizable and community-driven.',
  'https://stability.ai/stable-diffusion',
  'Image Generation',
  ARRAY['Text to Image', 'Open Source', 'Local', 'Customizable'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://stability.ai/favicon.ico'
),
(
  'leonardo-ai',
  'AI-powered creative asset generation',
  'Leonardo.AI creates production-quality visual assets with unprecedented speed and consistency. Ideal for game assets, concept art, and illustrations.',
  'https://leonardo.ai',
  'Image Generation',
  ARRAY['Text to Image', 'Game Assets', 'Concept Art', 'Consistent Style'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://leonardo.ai/favicon.ico'
),
(
  'firefly',
  'Adobe''s generative AI',
  'Adobe Firefly generates images, text effects, and more with commercial safety. Integrated into Adobe Creative Cloud apps.',
  'https://www.adobe.com/products/firefly.html',
  'Image Generation',
  ARRAY['Text to Image', 'Adobe', 'Commercial Safe', 'Design'],
  ARRAY['Freemium', 'Cloud', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.adobe.com/favicon.ico'
),
(
  'canva-ai',
  'AI-powered design platform',
  'Canva''s AI features include text-to-image generation, Magic Eraser, background removal, and design suggestions. Perfect for non-designers.',
  'https://www.canva.com',
  'Image Generation',
  ARRAY['Text to Image', 'Design', 'Templates', 'Marketing'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.canva.com/favicon.ico'
),
(
  'playground-ai',
  'Free AI image creator',
  'Playground AI offers free AI image generation with a focus on ease of use. Create art, social media graphics, and more.',
  'https://playgroundai.com',
  'Image Generation',
  ARRAY['Text to Image', 'Free', 'Social Media', 'Easy to Use'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://playgroundai.com/favicon.ico'
),
(
  'bluewillow',
  'Free AI image generator',
  'BlueWillow generates images from text prompts for free. Accessed through Discord, similar to Midjourney but free.',
  'https://www.bluewillow.ai',
  'Image Generation',
  ARRAY['Text to Image', 'Free', 'Discord', 'Art'],
  ARRAY['Free', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.bluewillow.ai/favicon.ico'
),
(
  'photoroom',
  'AI photo editing and background removal',
  'PhotoRoom uses AI to remove backgrounds, generate backgrounds, and edit product photos instantly. Perfect for e-commerce.',
  'https://www.photoroom.com',
  'Image Generation',
  ARRAY['Photo Editing', 'Background Removal', 'E-commerce', 'Product Photos'],
  ARRAY['Freemium', 'Mobile App', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.photoroom.com/favicon.ico'
),
(
  'clipdrop',
  'AI-powered visual tools',
  'Clipdrop by Stability AI offers background removal, upscaling, relighting, and more. Professional-grade visual tools accessible to everyone.',
  'https://clipdrop.co',
  'Image Generation',
  ARRAY['Photo Editing', 'Background Removal', 'Upscaling', 'Relighting'],
  ARRAY['Freemium', 'Web App', 'Mobile App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://clipdrop.co/favicon.ico'
),

-- VIDEO GENERATION (8 agents)
(
  'runway',
  'AI-powered video editing and generation',
  'Runway offers AI tools for video generation, editing, and effects. Create videos from text, remove backgrounds, and more.',
  'https://runwayml.com',
  'Video Generation',
  ARRAY['Text to Video', 'Video Editing', 'AI Effects', 'Creative'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://runwayml.com/favicon.ico'
),
(
  'pika-labs',
  'Text-to-video generation',
  'Pika generates and edits videos from text prompts. Create 3D animations, anime, and more through Discord.',
  'https://pika.art',
  'Video Generation',
  ARRAY['Text to Video', 'Animation', '3D', 'Discord'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://pika.art/favicon.ico'
),
(
  'kling-ai',
  'Advanced AI video generation',
  'Kling AI generates high-quality videos from text and images. Known for realistic motion and long video generation.',
  'https://klingai.com',
  'Video Generation',
  ARRAY['Text to Video', 'Image to Video', 'High Quality', 'Realistic'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://klingai.com/favicon.ico'
),
(
  'synthesia',
  'AI video creation with avatars',
  'Synthesia creates professional videos with AI avatars from text. Perfect for training videos, product demos, and marketing.',
  'https://www.synthesia.io',
  'Video Generation',
  ARRAY['Text to Video', 'AI Avatars', 'Training', 'Marketing'],
  ARRAY['Paid', 'Cloud', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.synthesia.io/favicon.ico'
),
(
  'heygen',
  'AI video platform with talking avatars',
  'HeyGen creates videos with AI avatars that speak in multiple languages. Perfect for localization and personalized video content.',
  'https://www.heygen.com',
  'Video Generation',
  ARRAY['Text to Video', 'AI Avatars', 'Multilingual', 'Localization'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.heygen.com/favicon.ico'
),
(
  'descript',
  'Video editing powered by AI transcription',
  'Descript lets you edit video by editing text transcripts. Remove filler words, create AI voices, and collaborate easily.',
  'https://www.descript.com',
  'Video Generation',
  ARRAY['Video Editing', 'Transcription', 'AI Voice', 'Podcasting'],
  ARRAY['Freemium', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.descript.com/favicon.ico'
),
(
  'invideo-ai',
  'AI video creator from text',
  'InVideo AI generates complete videos from text prompts. Add voiceovers, music, and transitions automatically.',
  'https://invideo.io',
  'Video Generation',
  ARRAY['Text to Video', 'Marketing', 'Social Media', 'Automated'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://invideo.io/favicon.ico'
),
(
  'pictory',
  'AI video creation from scripts',
  'Pictory turns scripts and articles into engaging videos. Perfect for social media, YouTube, and marketing.',
  'https://pictory.ai',
  'Video Generation',
  ARRAY['Text to Video', 'Marketing', 'Social Media', 'Automated'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://pictory.ai/favicon.ico'
),

-- VOICE AI (10 agents)
(
  'elevenlabs',
  'AI voice generation and cloning',
  'ElevenLabs creates realistic AI voices with emotion and natural intonation. Clone voices, generate speech, and dub content.',
  'https://elevenlabs.io',
  'Voice AI',
  ARRAY['Text to Speech', 'Voice Cloning', 'Multilingual', 'Realistic'],
  ARRAY['Freemium', 'Cloud', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://elevenlabs.io/favicon.ico'
),
(
  'play-ht',
  'AI voice generator for conversational use',
  'Play.ht generates ultra-realistic AI voices for games, videos, podcasts, and more. Over 600 voices in 60+ languages.',
  'https://play.ht',
  'Voice AI',
  ARRAY['Text to Speech', 'Voice Cloning', 'Multilingual', 'Gaming'],
  ARRAY['Freemium', 'Cloud', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://play.ht/favicon.ico'
),
(
  'murf-ai',
  'AI voice generator for professionals',
  'Murf creates studio-quality voiceovers with AI. Perfect for presentations, videos, and e-learning.',
  'https://murf.ai',
  'Voice AI',
  ARRAY['Text to Speech', 'Voiceover', 'E-learning', 'Professional'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://murf.ai/favicon.ico'
),
(
  'resemble-ai',
  'AI voice cloning and generation',
  'Resemble AI creates custom AI voices and clones existing voices. Real-time voice conversion and emotional control.',
  'https://www.resemble.ai',
  'Voice AI',
  ARRAY['Text to Speech', 'Voice Cloning', 'Real-time', 'Emotion'],
  ARRAY['Paid', 'Cloud', 'API', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.resemble.ai/favicon.ico'
),
(
  'wellsaid',
  'AI voice studio for content creators',
  'WellSaid Labs creates lifelike AI voices for content creation. Real people''s voices, digital convenience.',
  'https://wellsaidlabs.com',
  'Voice AI',
  ARRAY['Text to Speech', 'Voiceover', 'Content Creation', 'Realistic'],
  ARRAY['Paid', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://wellsaidlabs.com/favicon.ico'
),
(
  'descript-overdub',
  'AI voice cloning for Descript',
  'Overdub by Descript creates an AI clone of your voice for editing. Fix mistakes or create new audio without re-recording.',
  'https://www.descript.com/overdub',
  'Voice AI',
  ARRAY['Voice Cloning', 'Audio Editing', 'Podcasting', 'Correction'],
  ARRAY['Paid', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.descript.com/favicon.ico'
),
(
  'speechify',
  'Text-to-speech for reading',
  'Speechify converts text to natural-sounding audio. Listen to articles, PDFs, emails, and more.',
  'https://speechify.com',
  'Voice AI',
  ARRAY['Text to Speech', 'Reading', 'Accessibility', 'Productivity'],
  ARRAY['Freemium', 'Mobile App', 'Browser Extension'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://speechify.com/favicon.ico'
),
(
  'naturalreaders',
  'Text-to-speech for personal and commercial use',
  'NaturalReader converts text to speech with natural-sounding voices. Use for learning, proofreading, or content creation.',
  'https://www.naturalreaders.com',
  'Voice AI',
  ARRAY['Text to Speech', 'Reading', 'Learning', 'Proofreading'],
  ARRAY['Freemium', 'Web App', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.naturalreaders.com/favicon.ico'
),
(
  'lovo-ai',
  'AI voice generator and text-to-speech',
  'Lovo creates realistic voiceovers with 500+ voices in 100 languages. Perfect for marketing, gaming, and audiobooks.',
  'https://www.lovo.ai',
  'Voice AI',
  ARRAY['Text to Speech', 'Voice Cloning', 'Multilingual', 'Marketing'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.lovo.ai/favicon.ico'
),
(
  'voice-ai',
  'Real-time AI voice changer',
  'Voice.ai changes your voice in real-time for gaming, streaming, and calls. Thousands of voices to choose from.',
  'https://voice.ai',
  'Voice AI',
  ARRAY['Voice Changing', 'Real-time', 'Gaming', 'Streaming'],
  ARRAY['Freemium', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://voice.ai/favicon.ico'
),

-- WORKFLOW AUTOMATION (12 agents)
(
  'n8n',
  'Fair-code workflow automation',
  'n8n is an extendable workflow automation tool. Connect 400+ apps, build custom integrations, and self-host for full control.',
  'https://n8n.io',
  'Workflow Automation',
  ARRAY['Automation', 'Integration', 'Open Source', 'Self-Hosted'],
  ARRAY['Open Source', 'Free', 'Self-Hosted', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://n8n.io/favicon.ico'
),
(
  'make',
  'Visual automation platform (formerly Integromat)',
  'Make connects apps and automates workflows with a visual interface. More powerful than Zapier with advanced logic.',
  'https://www.make.com',
  'Workflow Automation',
  ARRAY['Automation', 'Integration', 'Visual', 'No-Code'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.make.com/favicon.ico'
),
(
  'zapier',
  'Workflow automation for everyone',
  'Zapier connects 6000+ apps to automate workflows without code. The most popular automation platform.',
  'https://zapier.com',
  'Workflow Automation',
  ARRAY['Automation', 'Integration', 'No-Code', 'Popular'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://zapier.com/favicon.ico'
),
(
  'activepieces',
  'Open-source business automation',
  'Activepieces is an open-source Zapier alternative. Self-host or use the cloud. AI-powered automation with 100+ integrations.',
  'https://www.activepieces.com',
  'Workflow Automation',
  ARRAY['Automation', 'Integration', 'Open Source', 'AI-Powered'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.activepieces.com/favicon.ico'
),
(
  'pipedream',
  'Developer-first integration platform',
  'Pipedream connects APIs with code or no-code. Build workflows with 1000+ integrated apps and custom code.',
  'https://pipedream.com',
  'Workflow Automation',
  ARRAY['Automation', 'Integration', 'Developer', 'API'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://pipedream.com/favicon.ico'
),
(
  'tray-io',
  'Enterprise automation platform',
  'Tray.io provides enterprise-grade automation with AI, data transformation, and complex workflow capabilities.',
  'https://tray.io',
  'Workflow Automation',
  ARRAY['Automation', 'Enterprise', 'Integration', 'Data'],
  ARRAY['Paid', 'Cloud', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://tray.io/favicon.ico'
),
(
  'workato',
  'Enterprise automation and integration',
  'Workato combines enterprise automation, integration, and AI. Built for IT and business teams.',
  'https://www.workato.com',
  'Workflow Automation',
  ARRAY['Automation', 'Enterprise', 'Integration', 'AI'],
  ARRAY['Paid', 'Cloud', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.workato.com/favicon.ico'
),
(
  'integrately',
  'Simple automation for small businesses',
  'Integrately offers 1-click automation for 1000+ apps. Simpler and more affordable than Zapier.',
  'https://integrately.com',
  'Workflow Automation',
  ARRAY['Automation', 'Integration', 'Simple', 'Affordable'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://integrately.com/favicon.ico'
),
(
  'huginn',
  'Build agents that monitor and act on your behalf',
  'Huginn is a self-hosted system for building agents that perform automated tasks. Think IFTTT on steroids.',
  'https://github.com/huginn/huginn',
  'Workflow Automation',
  ARRAY['Automation', 'Open Source', 'Self-Hosted', 'Agents'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'node-red',
  'Low-code programming for event-driven applications',
  'Node-RED is a flow-based programming tool for wiring together hardware devices, APIs, and online services.',
  'https://nodered.org',
  'Workflow Automation',
  ARRAY['Automation', 'IoT', 'Open Source', 'Visual'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://nodered.org/favicon.ico'
),
(
  'temporal',
  'Durable execution for workflows',
  'Temporal is an open-source platform for building reliable, distributed applications with durable workflows.',
  'https://temporal.io',
  'Workflow Automation',
  ARRAY['Workflow Engine', 'Distributed', 'Open Source', 'Developer'],
  ARRAY['Open Source', 'Free', 'Self-Hosted', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://temporal.io/favicon.ico'
),
(
  'windmill',
  'Open-source developer platform for workflows',
  'Windmill turns scripts into workflows and UIs. Self-hostable alternative to Retool, Airplane, and n8n.',
  'https://www.windmill.dev',
  'Workflow Automation',
  ARRAY['Automation', 'Developer', 'Open Source', 'Scripts'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.windmill.dev/favicon.ico'
),

-- BONUS: DATA ANALYSIS, DESIGN, PRODUCTIVITY (5 agents)
(
  'julius-ai',
  'AI-powered data analysis',
  'Julius helps you analyze data, create visualizations, and generate reports through conversation. Upload data and ask questions.',
  'https://julius.ai',
  'Data Analysis',
  ARRAY['Data Analysis', 'Visualization', 'Chat', 'Reports'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://julius.ai/favicon.ico'
),
(
  'framer',
  'AI-powered website builder',
  'Framer''s AI generates complete websites from text prompts. Design, prototype, and publish production sites.',
  'https://www.framer.com',
  'Design Tools',
  ARRAY['Website Builder', 'AI Design', 'No-Code', 'Responsive'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.framer.com/favicon.ico'
),
(
  'uizard',
  'AI-powered UI design',
  'Uizard turns screenshots, mockups, and text prompts into editable designs. Perfect for rapid prototyping.',
  'https://uizard.io',
  'Design Tools',
  ARRAY['UI Design', 'Prototyping', 'AI Design', 'Mockups'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://uizard.io/favicon.ico'
),
(
  'otter-ai',
  'AI meeting assistant and transcription',
  'Otter.ai records meetings, transcribes in real-time, and generates summaries. Integrates with Zoom, Meet, and Teams.',
  'https://otter.ai',
  'Productivity',
  ARRAY['Transcription', 'Meetings', 'Summarization', 'Collaboration'],
  ARRAY['Freemium', 'Cloud', 'Mobile App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://otter.ai/favicon.ico'
),
(
  'fireflies-ai',
  'AI meeting note taker',
  'Fireflies.ai joins your meetings, records, transcribes, and summarizes. Search across all your meetings.',
  'https://fireflies.ai',
  'Productivity',
  ARRAY['Transcription', 'Meetings', 'Summarization', 'Search'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://fireflies.ai/favicon.ico'
)

ON CONFLICT (codename) DO NOTHING;
