-- Add 45 more unique AI agents to reach exactly 200 total
-- Focus on gaps and emerging tools

INSERT INTO public.products (
  codename,
  punchline,
  description,
  product_website,
  categories,
  tags,
  labels,
  user_id,
  approved,
  featured,
  logo_src
) VALUES

-- More Coding Tools (10)
(
  'bolt-new',
  'Full-stack web app generator',
  'Bolt.new by StackBlitz generates and deploys full-stack web applications instantly. Built on WebContainers technology.',
  'https://bolt.new',
  'Coding Assistants',
  ARRAY['Full-Stack', 'Web App', 'Deployment', 'Instant'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://bolt.new/favicon.ico'
),
(
  'v0-vercel',
  'AI-powered UI generator',
  'v0 by Vercel generates React components from text prompts. Copy, customize, and ship production-ready code.',
  'https://v0.dev',
  'Coding Assistants',
  ARRAY['UI Generation', 'React', 'Components', 'Vercel'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://v0.dev/favicon.ico'
),
(
  'cursor-composer',
  'Multi-file AI editor in Cursor',
  'Composer is Cursor''s AI that can edit multiple files, refactor codebases, and implement features across your entire project.',
  'https://cursor.sh/features',
  'Coding Assistants',
  ARRAY['Multi-file', 'Refactoring', 'Full Project', 'IDE'],
  ARRAY['Paid', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://cursor.sh/brand/icon.svg'
),
(
  'pieces-for-developers',
  'AI-powered code snippet manager',
  'Pieces saves, enriches, and reuses code snippets with AI context. Works offline with local LLMs.',
  'https://pieces.app',
  'Coding Assistants',
  ARRAY['Code Snippets', 'Context', 'Offline', 'Local LLMs'],
  ARRAY['Free', 'Desktop App', 'IDE Integration'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://pieces.app/favicon.ico'
),
(
  'mintlify-writer',
  'AI documentation writer',
  'Mintlify Writer generates documentation as you code. Auto-document functions, classes, and entire codebases.',
  'https://mintlify.com/writer',
  'Coding Assistants',
  ARRAY['Documentation', 'Auto-generate', 'Code Comments'],
  ARRAY['Freemium', 'VS Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://mintlify.com/favicon.ico'
),
(
  'mutable-ai',
  'AI accelerated software development',
  'Mutable AI provides AI autocomplete, one-click production code generation, and prompt-driven development.',
  'https://mutable.ai',
  'Coding Assistants',
  ARRAY['Code Generation', 'Autocomplete', 'Production Code'],
  ARRAY['Freemium', 'VS Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://mutable.ai/favicon.ico'
),
(
  'sweep-dev',
  'AI junior developer for GitHub',
  'Sweep is a GitHub bot that writes code, fixes bugs, and refactors based on GitHub issues. Your AI junior developer.',
  'https://sweep.dev',
  'Coding Assistants',
  ARRAY['GitHub', 'Automation', 'Bug Fixing', 'Refactoring'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://sweep.dev/favicon.ico'
),
(
  'code-llama',
  'Meta''s code generation model',
  'Code Llama is Meta''s open-source LLM for code generation. Available in 7B, 13B, and 34B parameters.',
  'https://github.com/facebookresearch/codellama',
  'Coding Assistants',
  ARRAY['Open Source', 'Code Generation', 'Local LLMs', 'Meta'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'coderabbit',
  'AI code review agent',
  'CodeRabbit provides context-aware code reviews on pull requests. Catches bugs, suggests improvements, and enforces standards.',
  'https://coderabbit.ai',
  'Coding Assistants',
  ARRAY['Code Review', 'Pull Requests', 'Quality', 'GitHub'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://coderabbit.ai/favicon.ico'
),
(
  'qodo-gen',
  'AI test generation (formerly CodiumAI)',
  'Qodo (formerly CodiumAI) generates comprehensive tests, finds edge cases, and improves code quality automatically.',
  'https://www.qodo.ai',
  'Coding Assistants',
  ARRAY['Testing', 'Test Generation', 'Quality', 'Edge Cases'],
  ARRAY['Freemium', 'VS Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.qodo.ai/favicon.ico'
),

-- Image Generation & Design (8)
(
  'ideogram',
  'AI image generator with text rendering',
  'Ideogram creates images with accurate text rendering. Perfect for logos, posters, and designs with text.',
  'https://ideogram.ai',
  'Image Generation',
  ARRAY['Text to Image', 'Text Rendering', 'Logos', 'Design'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://ideogram.ai/favicon.ico'
),
(
  'flux-ai',
  'Black Forest Labs image generation',
  'FLUX is a new image generation model by Black Forest Labs (Stable Diffusion creators). Multiple variants from dev to pro.',
  'https://blackforestlabs.ai',
  'Image Generation',
  ARRAY['Text to Image', 'High Quality', 'Open Weights'],
  ARRAY['Freemium', 'Cloud', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://blackforestlabs.ai/favicon.ico'
),
(
  'recraft-ai',
  'AI design tool with brand consistency',
  'Recraft generates images, illustrations, and icons with consistent style and brand guidelines.',
  'https://www.recraft.ai',
  'Image Generation',
  ARRAY['Design', 'Brand Consistency', 'Illustrations', 'Icons'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.recraft.ai/favicon.ico'
),
(
  'magnific-ai',
  'AI image upscaler and enhancer',
  'Magnific upscales and enhances images with incredible detail. Hallucinate realistic details at any resolution.',
  'https://magnific.ai',
  'Image Generation',
  ARRAY['Upscaling', 'Enhancement', 'Super Resolution'],
  ARRAY['Paid', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://magnific.ai/favicon.ico'
),
(
  'krea-ai',
  'Real-time AI image generation',
  'Krea generates and edits images in real-time as you type. Perfect for rapid iteration and creative exploration.',
  'https://www.krea.ai',
  'Image Generation',
  ARRAY['Real-time', 'Text to Image', 'Interactive'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.krea.ai/favicon.ico'
),
(
  'pika-pika',
  'AI image generator',
  'Pika is a text-to-image AI with focus on creative control and artistic outputs.',
  'https://pika.art/image',
  'Image Generation',
  ARRAY['Text to Image', 'Artistic', 'Creative'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://pika.art/favicon.ico'
),
(
  'stylar-ai',
  'AI-powered image composition',
  'Stylar combines AI generation with layer-based editing. Precise control over composition and style.',
  'https://www.stylar.ai',
  'Image Generation',
  ARRAY['Composition', 'Layers', 'Precise Control'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.stylar.ai/favicon.ico'
),
(
  'getimg-ai',
  'AI image generation suite',
  'GetImg.AI offers multiple AI models, inpainting, outpainting, and custom model training in one platform.',
  'https://getimg.ai',
  'Image Generation',
  ARRAY['Multi-model', 'Inpainting', 'Custom Training'],
  ARRAY['Freemium', 'Cloud', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://getimg.ai/favicon.ico'
),

-- Video & Audio (7)
(
  'sora',
  'OpenAI''s text-to-video model',
  'Sora creates realistic and imaginative video scenes from text instructions. Can generate videos up to 1 minute long.',
  'https://openai.com/sora',
  'Video Generation',
  ARRAY['Text to Video', 'OpenAI', 'High Quality', 'Long Form'],
  ARRAY['Waitlist', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://openai.com/favicon.ico'
),
(
  'luma-ai-dream-machine',
  'Fast AI video generation',
  'Luma Dream Machine creates high-quality videos from text and images in minutes. Fast and accessible.',
  'https://lumalabs.ai/dream-machine',
  'Video Generation',
  ARRAY['Text to Video', 'Fast', 'High Quality'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://lumalabs.ai/favicon.ico'
),
(
  'haiper-ai',
  'AI video generation for creators',
  'Haiper creates videos from text descriptions. Animate images and repaint videos with AI.',
  'https://haiper.ai',
  'Video Generation',
  ARRAY['Text to Video', 'Animation', 'Video Repainting'],
  ARRAY['Free', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://haiper.ai/favicon.ico'
),
(
  'suno-ai',
  'AI music generation',
  'Suno creates complete songs from text prompts. Generate vocals, instrumentals, and lyrics.',
  'https://www.suno.ai',
  'Music & Audio',
  ARRAY['Music Generation', 'Vocals', 'Lyrics', 'Text to Music'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.suno.ai/favicon.ico'
),
(
  'udio-ai',
  'AI music creation',
  'Udio generates full songs with vocals, instruments, and production. Create original music in any genre.',
  'https://www.udio.com',
  'Music & Audio',
  ARRAY['Music Generation', 'Vocals', 'Full Production'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.udio.com/favicon.ico'
),
(
  'audiocraft',
  'Meta''s AI audio generation',
  'AudioCraft is Meta''s suite for music, audio, and compression with AI. Includes MusicGen and AudioGen.',
  'https://audiocraft.metademolab.com',
  'Music & Audio',
  ARRAY['Music Generation', 'Audio Generation', 'Open Source', 'Meta'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'aiva-ai',
  'AI music composition assistant',
  'AIVA creates original music for games, films, and content. Compose in various genres and styles.',
  'https://www.aiva.ai',
  'Music & Audio',
  ARRAY['Music Composition', 'Soundtrack', 'Gaming'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.aiva.ai/favicon.ico'
),

-- Autonomous Agents & Research (8)
(
  'auto-gpt',
  'Autonomous GPT-4 agent',
  'Auto-GPT is an experimental autonomous agent that chains together GPT-4 calls to achieve any goal you set.',
  'https://github.com/Significant-Gravitas/AutoGPT',
  'autonomous_agents',
  ARRAY['Autonomous', 'GPT-4', 'Open Source', 'Experimental'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'babyagi',
  'Task-driven autonomous agent',
  'BabyAGI is an AI-powered task management system that creates, prioritizes, and executes tasks autonomously.',
  'https://github.com/yoheinakajima/babyagi',
  'autonomous_agents',
  ARRAY['Autonomous', 'Task Management', 'Open Source'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'gpt-researcher',
  'Autonomous research assistant',
  'GPT Researcher conducts comprehensive online research on any topic. Generates detailed reports with sources.',
  'https://github.com/assafelovic/gpt-researcher',
  'Research Agents',
  ARRAY['Research', 'Autonomous', 'Reports', 'Open Source'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.githubassets.com/favicons/favicon.svg'
),
(
  'perplexity-ai',
  'AI-powered answer engine',
  'Perplexity is an AI search engine that provides direct answers with cited sources. Better than traditional search.',
  'https://www.perplexity.ai',
  'Research Agents',
  ARRAY['Search', 'Research', 'Citations', 'Answers'],
  ARRAY['Freemium', 'Cloud', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.perplexity.ai/favicon.ico'
),
(
  'elicit-ai',
  'AI research assistant for papers',
  'Elicit helps researchers find, summarize, and extract data from academic papers. Built for scientific research.',
  'https://elicit.com',
  'Research Agents',
  ARRAY['Research', 'Academic', 'Papers', 'Summarization'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://elicit.com/favicon.ico'
),
(
  'consensus-ai',
  'AI search engine for research papers',
  'Consensus uses AI to search and summarize findings from 200M+ scientific papers. Get evidence-based answers.',
  'https://consensus.app',
  'Research Agents',
  ARRAY['Research', 'Academic', 'Papers', 'Evidence'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://consensus.app/favicon.ico'
),
(
  'metaphor-ai',
  'AI-powered semantic search',
  'Metaphor (now Exa) is a search engine built for AI agents. Find high-quality content through semantic understanding.',
  'https://exa.ai',
  'Research Agents',
  ARRAY['Search', 'Semantic', 'API', 'AI Agents'],
  ARRAY['Freemium', 'Cloud', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://exa.ai/favicon.ico'
),
(
  'chatgpt-plugins',
  'Extend ChatGPT with plugins',
  'ChatGPT Plugins connect ChatGPT to third-party APIs. Access real-time information, run computations, and use external services.',
  'https://openai.com/blog/chatgpt-plugins',
  'Chat Assistants',
  ARRAY['Plugins', 'Extensions', 'API', 'OpenAI'],
  ARRAY['Paid', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://openai.com/favicon.ico'
),

-- Productivity & Business Tools (12)
(
  'zapier-ai',
  'AI-powered automation in Zapier',
  'Zapier Central (AI) creates custom bots that automate work across your apps. Natural language automation.',
  'https://zapier.com/ai',
  'Workflow Automation',
  ARRAY['Automation', 'AI Bots', 'Natural Language'],
  ARRAY['Paid', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://zapier.com/favicon.ico'
),
(
  'tome-ai',
  'AI-powered storytelling',
  'Tome creates presentations, landing pages, and microsites with AI. Generate entire decks from prompts.',
  'https://tome.app',
  'Productivity',
  ARRAY['Presentations', 'Storytelling', 'Design', 'Marketing'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://tome.app/favicon.ico'
),
(
  'gamma-ai',
  'AI presentation maker',
  'Gamma creates beautiful presentations, docs, and websites with AI. No formatting required.',
  'https://gamma.app',
  'Productivity',
  ARRAY['Presentations', 'Documents', 'Design'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://gamma.app/favicon.ico'
),
(
  'beautiful-ai',
  'AI-powered presentation design',
  'Beautiful.ai creates professional presentations with smart templates that adapt to your content automatically.',
  'https://www.beautiful.ai',
  'Productivity',
  ARRAY['Presentations', 'Design', 'Templates'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.beautiful.ai/favicon.ico'
),
(
  'reclaim-ai',
  'AI calendar and scheduling',
  'Reclaim.ai automatically schedules your tasks, habits, and meetings for optimal productivity.',
  'https://reclaim.ai',
  'Productivity',
  ARRAY['Calendar', 'Scheduling', 'Time Management', 'Automation'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://reclaim.ai/favicon.ico'
),
(
  'motion-app',
  'AI-powered project and task manager',
  'Motion uses AI to build your daily schedule, manage projects, and optimize your time automatically.',
  'https://www.usemotion.com',
  'Productivity',
  ARRAY['Project Management', 'Scheduling', 'Time Management', 'AI'],
  ARRAY['Paid', 'Cloud', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.usemotion.com/favicon.ico'
),
(
  'notion-ai-projects',
  'AI project management in Notion',
  'Notion Projects combines AI, wikis, and project management. Plan sprints, track tasks, and collaborate.',
  'https://www.notion.so/product/projects',
  'Productivity',
  ARRAY['Project Management', 'Collaboration', 'AI', 'Wiki'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.notion.so/favicon.ico'
),
(
  'mem-ai',
  'Self-organizing workspace',
  'Mem uses AI to organize your notes and surface relevant information when you need it. Your AI knowledge assistant.',
  'https://get.mem.ai',
  'Productivity',
  ARRAY['Note Taking', 'Knowledge Management', 'AI Organization'],
  ARRAY['Paid', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://get.mem.ai/favicon.ico'
),
(
  'taskade',
  'AI-powered productivity workspace',
  'Taskade combines AI chat, task management, and collaboration. Build custom AI agents for your workflows.',
  'https://www.taskade.com',
  'Productivity',
  ARRAY['Task Management', 'Collaboration', 'AI Agents', 'Chat'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.taskade.com/favicon.ico'
),
(
  'tldv-ai',
  'AI meeting recorder for Zoom and Meet',
  'tl;dv records, transcribes, and summarizes your video calls. Integrates with CRM and collaboration tools.',
  'https://tldv.io',
  'Productivity',
  ARRAY['Meetings', 'Transcription', 'Summarization', 'CRM'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://tldv.io/favicon.ico'
),
(
  'grain-ai',
  'AI notes for customer meetings',
  'Grain records customer conversations, generates notes, and surfaces insights automatically. Perfect for sales and support.',
  'https://grain.com',
  'Productivity',
  ARRAY['Meetings', 'CRM', 'Sales', 'Customer Success'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://grain.com/favicon.ico'
),
(
  'superhuman-ai',
  'AI-powered email',
  'Superhuman uses AI to write emails, summarize threads, and help you reach inbox zero. The fastest email experience.',
  'https://superhuman.com',
  'Productivity',
  ARRAY['Email', 'AI Writing', 'Productivity', 'Speed'],
  ARRAY['Paid', 'Desktop App', 'Mobile App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://superhuman.com/favicon.ico'
)

ON CONFLICT (codename) DO NOTHING;
