-- Seed 50 More AI Agents for agents.tips
-- Categories: Writing Tools, Image Generators, Video AI, Voice AI, Automation, More Coding & Frameworks

-- Insert new categories
INSERT INTO public.categories (name, icon) VALUES
('Writing Tools', '✍️'),
('Image Generation', '🎨'),
('Video Generation', '🎬'),
('Voice AI', '🎙️'),
('Design Tools', '🎨'),
('Data Analysis', '📊')
ON CONFLICT (name) DO NOTHING;

-- Insert new labels
INSERT INTO public.labels (name) VALUES
('API'),
('No-Code'),
('Plugin'),
('Mobile App'),
('Subscription')
ON CONFLICT (name) DO NOTHING;

-- Insert new tags
INSERT INTO public.tags (name) VALUES
('Text-to-Image'),
('Image-to-Image'),
('Text-to-Video'),
('Text-to-Speech'),
('Speech-to-Text'),
('Voice Cloning'),
('SEO'),
('Marketing'),
('Design'),
('Animation'),
('3D Generation'),
('Music Generation'),
('Video Editing'),
('Transcription'),
('Translation'),
('Summarization'),
('Email Automation'),
('Social Media'),
('Scheduling'),
('Data Extraction')
ON CONFLICT (name) DO NOTHING;

-- Insert 50 New AI Agent Products
INSERT INTO public.products (
  codename,
  punchline,
  description,
  product_website,
  categories,
  tags,
  labels,
  user_id,
  approved,
  featured,
  logo_src
) VALUES

-- WRITING TOOLS (10)
(
  'jasper',
  'AI content platform for marketing teams',
  'Jasper is an AI writing assistant for creating blog posts, marketing copy, social media content, and more. Trained on best practices, it helps teams produce high-quality content 10x faster.',
  'https://jasper.ai',
  'Writing Tools',
  ARRAY['Marketing', 'SEO', 'Content Creation'],
  ARRAY['Paid', 'Subscription', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.jasper.ai/favicon.ico'
),
(
  'copy-ai',
  'AI copywriter for sales and marketing',
  'Copy.ai generates marketing copy, product descriptions, emails, and social media posts. Built for sales and marketing teams who need to scale content production.',
  'https://copy.ai',
  'Writing Tools',
  ARRAY['Marketing', 'Content Creation', 'Email Automation'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.copy.ai/favicon.ico'
),
(
  'writesonic',
  'AI writing for blog posts, ads, and emails',
  'Writesonic is an AI writing tool that creates SEO-optimized blog posts, Google ads, landing pages, and more. Includes plagiarism checking and AI article writer.',
  'https://writesonic.com',
  'Writing Tools',
  ARRAY['SEO', 'Marketing', 'Content Creation'],
  ARRAY['Freemium', 'Web App', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://writesonic.com/favicon.ico'
),
(
  'grammarly',
  'AI writing assistant for clarity and correctness',
  'Grammarly checks grammar, spelling, punctuation, and style in real-time. AI-powered suggestions help improve clarity, engagement, and delivery across all your writing.',
  'https://grammarly.com',
  'Writing Tools',
  ARRAY['Documentation'],
  ARRAY['Freemium', 'Browser Extension', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://static.grammarly.com/assets/files/cda47f028fbb46d3fa70c9abb9681864/favicon.svg'
),
(
  'notion-ai',
  'AI assistant inside Notion',
  'Notion AI helps you write, brainstorm, edit, summarize, and translate — all inside your Notion workspace. Perfect for teams already using Notion for docs and knowledge management.',
  'https://notion.so/product/ai',
  'Writing Tools',
  ARRAY['Summarization', 'Translation', 'Content Creation'],
  ARRAY['Paid', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.notion.so/images/favicon.ico'
),
(
  'chatgpt',
  'Conversational AI from OpenAI',
  'ChatGPT is a conversational AI that can write, analyze, brainstorm, and solve problems. Powers everything from customer service to creative writing to coding assistance.',
  'https://chat.openai.com',
  'Chat Assistants',
  ARRAY['OpenAI', 'Content Creation', 'Code Generation'],
  ARRAY['Freemium', 'Web App', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://cdn.oaistatic.com/_next/static/media/apple-touch-icon.59f2e898.png'
),
(
  'claude',
  'AI assistant by Anthropic',
  'Claude is Anthropic''s AI assistant with extended thinking, vision, and coding capabilities. Known for being helpful, harmless, and honest — ideal for analysis, writing, and coding.',
  'https://claude.ai',
  'Chat Assistants',
  ARRAY['Anthropic', 'Content Creation', 'Code Generation', 'Data Analysis'],
  ARRAY['Freemium', 'Web App', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://claude.ai/favicon.ico'
),
(
  'wordtune',
  'AI writing companion for rewriting',
  'Wordtune helps you rewrite and rephrase sentences to make them clearer, more engaging, or match your tone. Built for writers who want to refine their voice.',
  'https://wordtune.com',
  'Writing Tools',
  ARRAY['Content Creation'],
  ARRAY['Freemium', 'Browser Extension', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.wordtune.com/favicon.ico'
),
(
  'quillbot',
  'AI paraphrasing and summarization tool',
  'QuillBot paraphrases text, checks grammar, and summarizes articles. Popular with students and writers for improving clarity and avoiding plagiarism.',
  'https://quillbot.com',
  'Writing Tools',
  ARRAY['Summarization'],
  ARRAY['Freemium', 'Web App', 'Browser Extension'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://quillbot.com/favicon.ico'
),
(
  'rytr',
  'AI writing assistant for everyone',
  'Rytr is an affordable AI writing tool for emails, blogs, ads, and social media. Supports 30+ languages and 20+ tones of voice.',
  'https://rytr.me',
  'Writing Tools',
  ARRAY['Marketing', 'Content Creation', 'Translation'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://rytr.me/favicon.ico'
),

-- IMAGE GENERATION (10)
(
  'midjourney',
  'AI art generation via Discord',
  'Midjourney creates stunning AI-generated art from text prompts. Known for artistic, high-quality images, it''s the go-to tool for designers, artists, and creators.',
  'https://midjourney.com',
  'Image Generation',
  ARRAY['Text-to-Image', 'Design'],
  ARRAY['Paid', 'Subscription', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.midjourney.com/apple-touch-icon.png'
),
(
  'dall-e',
  'OpenAI''s image generation model',
  'DALL·E creates realistic images and art from natural language descriptions. Integrated into ChatGPT, it can generate, edit, and remix images with precision.',
  'https://openai.com/dall-e',
  'Image Generation',
  ARRAY['Text-to-Image', 'Image-to-Image', 'OpenAI'],
  ARRAY['Paid', 'API', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://openai.com/favicon.ico'
),
(
  'stable-diffusion',
  'Open-source image generation model',
  'Stable Diffusion is an open-source text-to-image model you can run locally or in the cloud. Powers countless AI art tools and can be fine-tuned for custom styles.',
  'https://stability.ai/stable-diffusion',
  'Image Generation',
  ARRAY['Text-to-Image', 'Image-to-Image', 'Local LLMs'],
  ARRAY['Open Source', 'Free', 'Self-Hosted'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://stability.ai/favicon.ico'
),
(
  'leonardo-ai',
  'AI image generator for creators',
  'Leonardo.ai generates game assets, concept art, and illustrations. Offers fine control over composition, style, and quality with custom models.',
  'https://leonardo.ai',
  'Image Generation',
  ARRAY['Text-to-Image', 'Image-to-Image', 'Design'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://leonardo.ai/favicon.ico'
),
(
  'firefly',
  'Adobe''s generative AI for creatives',
  'Adobe Firefly generates images, text effects, and design elements — all commercially safe. Integrated into Photoshop, Illustrator, and Creative Cloud.',
  'https://firefly.adobe.com',
  'Image Generation',
  ARRAY['Text-to-Image', 'Design'],
  ARRAY['Freemium', 'Web App', 'Plugin'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://firefly.adobe.com/favicon.ico'
),
(
  'playground-ai',
  'Free AI image creator',
  'Playground AI is a free image generation tool with advanced editing features. Create, mix, and refine images with an intuitive canvas interface.',
  'https://playgroundai.com',
  'Image Generation',
  ARRAY['Text-to-Image', 'Image-to-Image'],
  ARRAY['Free', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://playgroundai.com/favicon.ico'
),
(
  'bluewillow',
  'AI art generator for everyone',
  'BlueWillow generates AI images through Discord, similar to Midjourney but free. Great for beginners and hobbyists exploring AI art.',
  'https://bluewillow.ai',
  'Image Generation',
  ARRAY['Text-to-Image'],
  ARRAY['Free', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.bluewillow.ai/favicon.ico'
),
(
  'artbreeder',
  'Collaborative AI art creation',
  'Artbreeder lets you create and remix images using AI. Blend portraits, landscapes, and abstract art, then share and collaborate with a creative community.',
  'https://artbreeder.com',
  'Image Generation',
  ARRAY['Image-to-Image', 'Design'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.artbreeder.com/favicon.ico'
),
(
  'nightcafe',
  'AI art generator with multiple models',
  'NightCafe offers multiple AI art generation algorithms (Stable Diffusion, DALL·E, etc) in one place. Create, own, and print your AI art.',
  'https://nightcafe.studio',
  'Image Generation',
  ARRAY['Text-to-Image', 'Image-to-Image'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://creator.nightcafe.studio/favicon.ico'
),
(
  'getimg-ai',
  'AI image suite for everything',
  'Getimg.ai offers image generation, editing, inpainting, and AI models — all in one platform. Built for designers who need flexible AI image tools.',
  'https://getimg.ai',
  'Image Generation',
  ARRAY['Text-to-Image', 'Image-to-Image'],
  ARRAY['Freemium', 'Web App', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://getimg.ai/favicon.ico'
),

-- VIDEO GENERATION (8)
(
  'runway',
  'AI video generation and editing',
  'Runway is a video generation platform with text-to-video, image-to-video, motion tracking, and AI editing tools. Used by filmmakers and content creators.',
  'https://runwayml.com',
  'Video Generation',
  ARRAY['Text-to-Video', 'Video Editing'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://runwayml.com/favicon.ico'
),
(
  'pika',
  'Idea-to-video platform',
  'Pika turns text and images into videos. Create, edit, and remix video clips with simple prompts — no video editing experience needed.',
  'https://pika.art',
  'Video Generation',
  ARRAY['Text-to-Video'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://pika.art/favicon.ico'
),
(
  'synthesia',
  'AI video generation with avatars',
  'Synthesia creates professional videos with AI avatars and voiceovers. Type your script, choose an avatar, and generate training videos or presentations.',
  'https://synthesia.io',
  'Video Generation',
  ARRAY['Text-to-Speech', 'Marketing'],
  ARRAY['Paid', 'Web App', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.synthesia.io/favicon.ico'
),
(
  'heygen',
  'AI video generator with realistic avatars',
  'HeyGen creates personalized videos with AI avatars that speak any language. Perfect for marketing, training, and localized content at scale.',
  'https://heygen.com',
  'Video Generation',
  ARRAY['Text-to-Speech', 'Translation', 'Marketing'],
  ARRAY['Paid', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.heygen.com/favicon.ico'
),
(
  'descript',
  'Video and podcast editing by text',
  'Descript lets you edit video and audio by editing text. Includes AI transcription, voice cloning, filler word removal, and overdub.',
  'https://descript.com',
  'Video Generation',
  ARRAY['Transcription', 'Voice Cloning', 'Video Editing'],
  ARRAY['Freemium', 'Desktop App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.descript.com/favicon.ico'
),
(
  'fliki',
  'Text to video with AI voices',
  'Fliki converts blog posts, tweets, and scripts into videos with AI voiceovers. Includes stock media and supports 75+ languages.',
  'https://fliki.ai',
  'Video Generation',
  ARRAY['Text-to-Video', 'Text-to-Speech'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://fliki.ai/favicon.ico'
),
(
  'invideo-ai',
  'AI video creation from prompts',
  'InVideo AI generates full videos from text prompts — including script, voiceover, visuals, and music. Built for content creators and marketers.',
  'https://invideo.ai',
  'Video Generation',
  ARRAY['Text-to-Video', 'Marketing'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://invideo.ai/favicon.ico'
),
(
  'pictory',
  'AI video creation for long-form content',
  'Pictory turns articles and long-form content into short, shareable videos. Auto-generates captions and highlights key moments for social media.',
  'https://pictory.ai',
  'Video Generation',
  ARRAY['Text-to-Video', 'Social Media'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://pictory.ai/favicon.ico'
),

-- VOICE AI (7)
(
  'elevenlabs',
  'AI voice generation and cloning',
  'ElevenLabs generates realistic AI voices and clones your voice from minutes of audio. Used for audiobooks, dubbing, and content creation.',
  'https://elevenlabs.io',
  'Voice AI',
  ARRAY['Text-to-Speech', 'Voice Cloning', 'Translation'],
  ARRAY['Freemium', 'API', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://elevenlabs.io/favicon.ico'
),
(
  'play-ht',
  'AI voice generator for text-to-speech',
  'Play.ht converts text to realistic speech with 600+ AI voices in 142 languages. API and web interface for podcasts, videos, and more.',
  'https://play.ht',
  'Voice AI',
  ARRAY['Text-to-Speech'],
  ARRAY['Freemium', 'API', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://play.ht/favicon.ico'
),
(
  'murf-ai',
  'AI voiceover studio',
  'Murf.ai creates studio-quality voiceovers from text. Choose from 120+ voices, customize pitch and emphasis, and sync to video.',
  'https://murf.ai',
  'Voice AI',
  ARRAY['Text-to-Speech'],
  ARRAY['Freemium', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://murf.ai/favicon.ico'
),
(
  'resemble-ai',
  'Voice cloning and synthesis',
  'Resemble AI clones voices with high fidelity for gaming, entertainment, and customer service. Real-time voice conversion and emotional control.',
  'https://resemble.ai',
  'Voice AI',
  ARRAY['Voice Cloning', 'Text-to-Speech'],
  ARRAY['Paid', 'API', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.resemble.ai/favicon.ico'
),
(
  'speechify',
  'Text-to-speech for reading',
  'Speechify reads any text aloud with natural AI voices. Popular for accessibility, studying, and consuming written content on the go.',
  'https://speechify.com',
  'Voice AI',
  ARRAY['Text-to-Speech'],
  ARRAY['Freemium', 'Mobile App', 'Browser Extension'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://speechify.com/favicon.ico'
),
(
  'whisper',
  'OpenAI speech recognition',
  'Whisper is OpenAI''s open-source speech-to-text model. Supports 99 languages, handles accents and background noise, and runs locally.',
  'https://openai.com/research/whisper',
  'Voice AI',
  ARRAY['Speech-to-Text', 'Transcription', 'OpenAI'],
  ARRAY['Open Source', 'Free', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://openai.com/favicon.ico'
),
(
  'otter-ai',
  'AI meeting transcription',
  'Otter.ai transcribes meetings, interviews, and lectures in real-time. Includes speaker identification, highlights, and searchable transcripts.',
  'https://otter.ai',
  'Voice AI',
  ARRAY['Speech-to-Text', 'Transcription'],
  ARRAY['Freemium', 'Web App', 'Mobile App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://otter.ai/favicon.ico'
),

-- AUTOMATION PLATFORMS (8)
(
  'zapier',
  'Workflow automation for everyone',
  'Zapier connects 6,000+ apps to automate workflows without code. Trigger actions, move data, and build multi-step workflows between your favorite tools.',
  'https://zapier.com',
  'Workflow Automation',
  ARRAY['Web Automation', 'Email Automation', 'Task Planning'],
  ARRAY['Freemium', 'Cloud', 'No-Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://cdn.zappy.app/8f7e4b8d8b8f8f8f8f8f8f8f8f8f8f8f.svg'
),
(
  'make',
  'Visual automation platform',
  'Make (formerly Integromat) is a visual automation platform for complex workflows. Build scenarios with drag-and-drop, API calls, and custom logic.',
  'https://make.com',
  'Workflow Automation',
  ARRAY['Web Automation', 'Task Planning', 'API'],
  ARRAY['Freemium', 'Cloud', 'No-Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.make.com/en/favicon.ico'
),
(
  'n8n',
  'Self-hosted workflow automation',
  'n8n is an open-source alternative to Zapier. Build complex automations with 350+ integrations, custom code, and full data privacy.',
  'https://n8n.io',
  'Workflow Automation',
  ARRAY['Web Automation', 'Task Planning'],
  ARRAY['Open Source', 'Self-Hosted', 'No-Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://n8n.io/favicon.ico'
),
(
  'activepieces',
  'Open-source business automation',
  'Activepieces is a self-hostable no-code automation tool. Connect apps, AI models, and databases to automate business processes.',
  'https://activepieces.com',
  'Workflow Automation',
  ARRAY['Web Automation', 'Task Planning'],
  ARRAY['Open Source', 'Self-Hosted', 'No-Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.activepieces.com/favicon.ico'
),
(
  'bardeen',
  'Browser automation with AI',
  'Bardeen automates browser workflows with AI. Scrape data, fill forms, and connect web apps — all from a Chrome extension.',
  'https://bardeen.ai',
  'Workflow Automation',
  ARRAY['Web Automation', 'Data Extraction'],
  ARRAY['Freemium', 'Browser Extension'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.bardeen.ai/favicon.ico'
),
(
  'relay',
  'Deep workflow automation',
  'Relay combines automation with AI assistance. Build workflows that involve human collaboration, AI steps, and conditional logic.',
  'https://relay.app',
  'Workflow Automation',
  ARRAY['Web Automation', 'Task Planning'],
  ARRAY['Freemium', 'Cloud', 'No-Code'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://relay.app/favicon.ico'
),
(
  'pipedream',
  'Connect APIs fast with code',
  'Pipedream is a developer-first integration platform. Build workflows with pre-built actions or custom Node.js code, trigger on any event.',
  'https://pipedream.com',
  'Workflow Automation',
  ARRAY['API', 'Web Automation'],
  ARRAY['Freemium', 'Cloud'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://pipedream.com/favicon.ico'
),
(
  'temporal',
  'Durable execution for workflows',
  'Temporal is an open-source orchestration platform for building reliable distributed systems. Write workflows as code with automatic retries and state management.',
  'https://temporal.io',
  'Workflow Automation',
  ARRAY['Task Planning', 'Agentic Workflow'],
  ARRAY['Open Source', 'Self-Hosted', 'Enterprise'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://temporal.io/favicon.ico'
),

-- MORE CODING & AI FRAMEWORKS (7)
(
  'perplexity',
  'AI-powered research assistant',
  'Perplexity is an AI search engine that answers questions with citations. Combines search, synthesis, and conversational AI for research.',
  'https://perplexity.ai',
  'Research Agents',
  ARRAY['Data Analysis', 'Summarization'],
  ARRAY['Freemium', 'Web App', 'API'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://www.perplexity.ai/favicon.svg'
),
(
  'phind',
  'AI search for developers',
  'Phind is an AI search engine built for developers. Get instant answers with code examples, explanations, and links to documentation.',
  'https://phind.com',
  'Research Agents',
  ARRAY['Code Generation', 'Documentation'],
  ARRAY['Free', 'Web App'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.phind.com/favicon.ico'
),
(
  'semantic-kernel',
  'Microsoft''s AI orchestration SDK',
  'Semantic Kernel is Microsoft''s SDK for integrating AI into apps. Orchestrate LLMs, plugins, and memory with C#, Python, or Java.',
  'https://github.com/microsoft/semantic-kernel',
  'AI Frameworks',
  ARRAY['Multi-Agent', 'Context Management'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://github.com/microsoft.png'
),
(
  'autogen',
  'Multi-agent conversation framework',
  'AutoGen enables development of LLM applications using multiple agents that can converse with each other to solve tasks. From Microsoft Research.',
  'https://microsoft.github.io/autogen',
  'AI Frameworks',
  ARRAY['Multi-Agent', 'Agentic Workflow', 'Task Planning'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  true,
  'https://microsoft.github.io/autogen/favicon.ico'
),
(
  'llamaindex',
  'Data framework for LLM apps',
  'LlamaIndex is a data framework for connecting custom data to LLMs. Build RAG pipelines, knowledge bases, and AI-powered search.',
  'https://llamaindex.ai',
  'AI Frameworks',
  ARRAY['Context Management', 'Data Analysis'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://www.llamaindex.ai/favicon.ico'
),
(
  'haystack',
  'LLM orchestration framework',
  'Haystack is an open-source framework for building search and question-answering systems with LLMs. Includes pipelines, retrievers, and agents.',
  'https://haystack.deepset.ai',
  'AI Frameworks',
  ARRAY['Context Management', 'Data Analysis'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://haystack.deepset.ai/favicon.ico'
),
(
  'litellm',
  'Unified API for 100+ LLMs',
  'LiteLLM provides a unified interface to call 100+ LLMs (OpenAI, Anthropic, Cohere, etc) with the same API. Simplifies multi-model apps.',
  'https://litellm.ai',
  'AI Frameworks',
  ARRAY['OpenAI', 'Anthropic', 'API'],
  ARRAY['Open Source', 'Free'],
  '00000000-0000-0000-0000-000000000001',
  true,
  false,
  'https://litellm.ai/favicon.ico'
)

ON CONFLICT (codename) DO NOTHING;
