-- Seed Additional 50 AI Agents for agents.tips
-- Focus on: Business Tools, Productivity, Customer Service, Education, Legal, Healthcare, Finance

-- Insert additional categories
INSERT INTO public.categories (name, icon) VALUES
('Business Intelligence', '📊'),
('Customer Service', '👥'),
('Education', '📚'),
('Legal Tech', '⚖️'),
('Healthcare AI', '🏥'),
('Finance AI', '💰'),
('HR & Recruitment', '👔'),
('Sales Tools', '💼'),
('Research Tools', '🔬'),
('Translation', '🌐')
ON CONFLICT (name) DO NOTHING;

-- Insert additional labels
INSERT INTO public.labels (name) VALUES
('Enterprise'),
('Small Business'),
('Startup'),
('Self-Hosted'),
('Chrome Extension'),
('Desktop App')
ON CONFLICT (name) DO NOTHING;

-- Insert additional tags
INSERT INTO public.tags (name) VALUES
('Customer Support'),
('Chatbot'),
('Analytics'),
('CRM'),
('Email'),
('Document Analysis'),
('Legal Documents'),
('Medical Diagnosis'),
('Financial Analysis'),
('HR Automation'),
('Recruiting'),
('Sales Forecasting'),
('Lead Generation'),
('Knowledge Base'),
('Training'),
('E-learning'),
('Language Learning'),
('Research Assistant'),
('Citation Management'),
('Data Visualization')
ON CONFLICT (name) DO NOTHING;

-- Insert 50+ Additional AI Agent Products
INSERT INTO public.products (
  codename,
  punchline,
  description,
  product_website,
  categories,
  tags,
  labels,
  user_id,
  approved,
  featured,
  logo_src
) VALUES

-- BUSINESS INTELLIGENCE (5)
(
  'tableau-ai',
  'AI-powered data visualization and analytics',
  'Tableau integrates AI to help analyze data, create visualizations, and generate insights automatically. Ask questions in natural language and get instant visual answers.',
  'https://tableau.com',
  'Business Intelligence',
  ARRAY['Analytics', 'Data Visualization', 'Business Intelligence'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.tableau.com/favicon.ico'
),
(
  'power-bi-copilot',
  'Microsoft AI assistant for business analytics',
  'Power BI Copilot helps create reports, analyze data, and generate insights using natural language. Integrated with Microsoft 365 ecosystem.',
  'https://powerbi.microsoft.com',
  'Business Intelligence',
  ARRAY['Analytics', 'Data Visualization', 'Automation'],
  ARRAY['Enterprise', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://powerbi.microsoft.com/favicon.ico'
),
(
  'thoughtspot',
  'AI-powered search and analytics platform',
  'ThoughtSpot uses AI to let anyone search data like Google. Ask questions, get instant visualizations, and uncover insights without technical knowledge.',
  'https://thoughtspot.com',
  'Business Intelligence',
  ARRAY['Analytics', 'Search', 'Data Visualization'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.thoughtspot.com/favicon.ico'
),
(
  'looker-ai',
  'Google Cloud AI analytics platform',
  'Looker with AI capabilities provides embedded analytics, real-time dashboards, and predictive insights for data-driven decision making.',
  'https://cloud.google.com/looker',
  'Business Intelligence',
  ARRAY['Analytics', 'Data Visualization', 'Cloud'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://cloud.google.com/favicon.ico'
),
(
  'sisense-ai',
  'AI-powered embedded analytics',
  'Sisense uses AI to help embed analytics into products, automate insights, and predict trends. Built for product teams and SaaS companies.',
  'https://sisense.com',
  'Business Intelligence',
  ARRAY['Analytics', 'Data Visualization', 'Embedding'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.sisense.com/favicon.ico'
),

-- CUSTOMER SERVICE (10)
(
  'intercom-fin',
  'AI customer support chatbot',
  'Fin by Intercom is an AI chatbot that resolves 50% of customer inquiries instantly. Uses GPT-4 and your knowledge base to provide accurate answers.',
  'https://intercom.com/fin',
  'Customer Service',
  ARRAY['Chatbot', 'Customer Support', 'Automation'],
  ARRAY['Paid', 'Subscription', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.intercom.com/favicon.ico'
),
(
  'zendesk-ai',
  'AI-powered customer service platform',
  'Zendesk AI automates ticket routing, suggests responses, and provides sentiment analysis. Integrated with the full Zendesk suite.',
  'https://zendesk.com',
  'Customer Service',
  ARRAY['Customer Support', 'Automation', 'CRM'],
  ARRAY['Enterprise', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.zendesk.com/favicon.ico'
),
(
  'ada-support',
  'Automated customer service platform',
  'Ada is an AI chatbot that handles complex customer conversations across channels. No code required, integrates with existing tools.',
  'https://ada.cx',
  'Customer Service',
  ARRAY['Chatbot', 'Customer Support', 'No-Code'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://ada.cx/favicon.ico'
),
(
  'freshdesk-freddy',
  'AI assistant for customer support',
  'Freddy AI by Freshdesk predicts ticket priority, suggests solutions, and automates repetitive tasks. Part of Freshworks customer service suite.',
  'https://freshdesk.com',
  'Customer Service',
  ARRAY['Customer Support', 'Automation', 'Ticketing'],
  ARRAY['Freemium', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://freshdesk.com/favicon.ico'
),
(
  'kustomer',
  'AI-powered CRM for customer service',
  'Kustomer uses AI to provide a complete customer view, automate workflows, and predict customer needs. Built for modern support teams.',
  'https://kustomer.com',
  'Customer Service',
  ARRAY['CRM', 'Customer Support', 'Automation'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.kustomer.com/favicon.ico'
),
(
  'forethought-ai',
  'AI for customer support automation',
  'Forethought automates ticket routing, provides instant answers, and assists agents in real-time. Integrates with major helpdesk platforms.',
  'https://forethought.ai',
  'Customer Service',
  ARRAY['Customer Support', 'Automation', 'Ticketing'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://forethought.ai/favicon.ico'
),
(
  'helpscout-beacon',
  'AI-powered help desk software',
  'Help Scout uses AI to suggest articles, automate responses, and provide customer insights. Beautiful, human-first customer support.',
  'https://helpscout.com',
  'Customer Service',
  ARRAY['Customer Support', 'Knowledge Base', 'Email'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.helpscout.com/favicon.ico'
),
(
  'drift',
  'Conversational AI for sales and support',
  'Drift uses AI chatbots to qualify leads, book meetings, and answer customer questions 24/7. Conversational marketing platform.',
  'https://drift.com',
  'Customer Service,Sales Tools',
  ARRAY['Chatbot', 'Lead Generation', 'Customer Support'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.drift.com/favicon.ico'
),
(
  'tidio',
  'AI chatbot for customer service',
  'Tidio combines live chat, chatbots, and marketing automation. AI-powered bots answer questions and qualify leads automatically.',
  'https://tidio.com',
  'Customer Service',
  ARRAY['Chatbot', 'Customer Support', 'Live Chat'],
  ARRAY['Freemium', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.tidio.com/favicon.ico'
),
(
  'liveperson',
  'AI-powered conversational platform',
  'LivePerson uses conversational AI to automate customer interactions across messaging channels. Enterprise-grade platform.',
  'https://liveperson.com',
  'Customer Service',
  ARRAY['Chatbot', 'Customer Support', 'Messaging'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.liveperson.com/favicon.ico'
),

-- EDUCATION (8)
(
  'khan-academy-khanmigo',
  'AI tutor for personalized learning',
  'Khanmigo is Khan Academy AI tutor powered by GPT-4. Provides personalized tutoring, helps with homework, and adapts to learning style.',
  'https://khanacademy.org/khanmigo',
  'Education',
  ARRAY['E-learning', 'Training', 'Personalization'],
  ARRAY['Freemium', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://cdn.kastatic.org/images/favicon.ico'
),
(
  'duolingo-max',
  'AI-powered language learning',
  'Duolingo Max uses GPT-4 to provide personalized explanations, role-play conversations, and adaptive language learning experiences.',
  'https://duolingo.com',
  'Education',
  ARRAY['Language Learning', 'E-learning', 'Personalization'],
  ARRAY['Freemium', 'Mobile App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.duolingo.com/favicon.ico'
),
(
  'quizlet-q-chat',
  'AI study assistant',
  'Q-Chat by Quizlet is an AI tutor that helps students study by providing explanations, practice questions, and personalized learning paths.',
  'https://quizlet.com',
  'Education',
  ARRAY['E-learning', 'Training', 'Study Tools'],
  ARRAY['Freemium', 'Web App', 'Mobile App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.quizlet.com/favicon.ico'
),
(
  'gradescope',
  'AI-assisted grading platform',
  'Gradescope uses AI to help grade assignments, exams, and homework efficiently. Provides analytics and saves instructors hours of time.',
  'https://gradescope.com',
  'Education',
  ARRAY['Grading', 'Analytics', 'Automation'],
  ARRAY['Paid', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.gradescope.com/favicon.ico'
),
(
  'squirrel-ai',
  'Adaptive learning platform',
  'Squirrel AI provides personalized K-12 tutoring using adaptive learning algorithms. Identifies knowledge gaps and creates custom learning paths.',
  'https://squirrelai.com',
  'Education',
  ARRAY['E-learning', 'Training', 'Personalization'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://squirrelai.com/favicon.ico'
),
(
  'century-tech',
  'AI teaching and learning platform',
  'Century uses AI and neuroscience to provide personalized learning paths, track progress, and free up teacher time with insights.',
  'https://century.tech',
  'Education',
  ARRAY['E-learning', 'Analytics', 'Personalization'],
  ARRAY['Enterprise', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.century.tech/favicon.ico'
),
(
  'coursera-coach',
  'AI learning assistant',
  'Coursera Coach provides personalized course recommendations, study tips, and career guidance powered by AI.',
  'https://coursera.org',
  'Education',
  ARRAY['E-learning', 'Career', 'Personalization'],
  ARRAY['Freemium', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.coursera.org/favicon.ico'
),
(
  'synthesis-tutor',
  'AI tutor for complex problem solving',
  'Synthesis uses AI to teach kids critical thinking and problem-solving through collaborative games and challenges.',
  'https://synthesis.com',
  'Education',
  ARRAY['E-learning', 'Critical Thinking', 'Games'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://synthesis.com/favicon.ico'
),

-- LEGAL TECH (5)
(
  'harvey-ai',
  'AI copilot for legal work',
  'Harvey is an AI legal assistant built for law firms. Helps with research, document drafting, analysis, and due diligence.',
  'https://harvey.ai',
  'Legal Tech',
  ARRAY['Legal Documents', 'Research', 'Document Analysis'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://harvey.ai/favicon.ico'
),
(
  'casetext-cocounsel',
  'AI legal research assistant',
  'CoCounsel by Casetext uses GPT-4 for legal research, document review, deposition preparation, and contract analysis.',
  'https://casetext.com',
  'Legal Tech',
  ARRAY['Legal Documents', 'Research', 'Document Analysis'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://casetext.com/favicon.ico'
),
(
  'lawgeex',
  'AI contract review platform',
  'Lawgeex automates contract review, identifies issues, and suggests changes based on company policies. Built for legal teams.',
  'https://lawgeex.com',
  'Legal Tech',
  ARRAY['Legal Documents', 'Contract Review', 'Automation'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.lawgeex.com/favicon.ico'
),
(
  'spellbook-legal',
  'AI-powered contract drafting',
  'Spellbook uses GPT-4 to help lawyers draft and review contracts faster. Integrates directly with Microsoft Word.',
  'https://spellbook.legal',
  'Legal Tech',
  ARRAY['Legal Documents', 'Contract Drafting', 'Microsoft Word'],
  ARRAY['Paid', 'Plugin'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://spellbook.legal/favicon.ico'
),
(
  'legalrobot',
  'AI for legal document analysis',
  'Legal Robot analyzes contracts and legal documents to identify issues, explain terms, and provide insights in plain language.',
  'https://legalrobot.com',
  'Legal Tech',
  ARRAY['Legal Documents', 'Document Analysis', 'Plain Language'],
  ARRAY['Paid', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://legalrobot.com/favicon.ico'
),

-- HEALTHCARE AI (5)
(
  'glass-health',
  'AI clinical decision support',
  'Glass Health helps doctors create differential diagnoses and clinical plans using AI. Built by physicians for physicians.',
  'https://glass.health',
  'Healthcare AI',
  ARRAY['Medical Diagnosis', 'Clinical Decision', 'Healthcare'],
  ARRAY['Paid', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://glass.health/favicon.ico'
),
(
  'nabla-copilot',
  'AI medical scribe and assistant',
  'Nabla Copilot automatically generates clinical notes from doctor-patient conversations. Saves doctors hours of documentation time.',
  'https://nabla.com',
  'Healthcare AI',
  ARRAY['Medical Notes', 'Transcription', 'Healthcare'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.nabla.com/favicon.ico'
),
(
  'path-ai',
  'AI-powered pathology',
  'PathAI uses AI to help pathologists make more accurate diagnoses from tissue samples. Improves cancer detection and treatment.',
  'https://pathai.com',
  'Healthcare AI',
  ARRAY['Medical Diagnosis', 'Pathology', 'Cancer Detection'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.pathai.com/favicon.ico'
),
(
  'butterfly-iq',
  'AI-powered ultrasound',
  'Butterfly iQ combines portable ultrasound with AI to guide image capture and assist with interpretation. Democratizing medical imaging.',
  'https://butterflynetwork.com',
  'Healthcare AI',
  ARRAY['Medical Imaging', 'Ultrasound', 'Diagnostic'],
  ARRAY['Paid', 'Hardware'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.butterflynetwork.com/favicon.ico'
),
(
  'k-health',
  'AI symptom checker and diagnosis',
  'K Health uses AI to analyze symptoms, provide possible diagnoses, and connect patients with doctors. Based on millions of patient cases.',
  'https://khealth.com',
  'Healthcare AI',
  ARRAY['Symptom Checker', 'Medical Diagnosis', 'Telemedicine'],
  ARRAY['Freemium', 'Mobile App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.khealth.com/favicon.ico'
),

-- FINANCE AI (5)
(
  'bloomberg-gpt',
  'AI for financial analysis',
  'BloombergGPT is a large language model trained on financial data. Helps analyze markets, generate reports, and answer financial questions.',
  'https://bloomberg.com',
  'Finance AI',
  ARRAY['Financial Analysis', 'Market Research', 'Reporting'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.bloomberg.com/favicon.ico'
),
(
  'affirm-ai',
  'AI-powered lending decisions',
  'Affirm uses AI to assess creditworthiness and provide instant lending decisions for consumers. Alternative to traditional credit scoring.',
  'https://affirm.com',
  'Finance AI',
  ARRAY['Credit Scoring', 'Lending', 'Risk Assessment'],
  ARRAY['Free', 'Web App', 'Mobile App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.affirm.com/favicon.ico'
),
(
  'kensho',
  'AI for investment analytics',
  'Kensho uses AI to analyze financial markets, extract data from documents, and provide investment insights. Part of S&P Global.',
  'https://kensho.com',
  'Finance AI',
  ARRAY['Financial Analysis', 'Investment', 'Data Extraction'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.kensho.com/favicon.ico'
),
(
  'plaid',
  'AI-powered financial data platform',
  'Plaid uses AI to connect financial accounts, verify identity, and assess risk. Powers thousands of fintech apps.',
  'https://plaid.com',
  'Finance AI',
  ARRAY['Financial Data', 'Identity Verification', 'API'],
  ARRAY['API', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://plaid.com/favicon.ico'
),
(
  'unit21',
  'AI fraud detection and prevention',
  'Unit21 uses AI to detect fraud, money laundering, and suspicious activity in real-time. Built for fintech and banks.',
  'https://unit21.ai',
  'Finance AI',
  ARRAY['Fraud Detection', 'Risk Assessment', 'Compliance'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://unit21.ai/favicon.ico'
),

-- HR & RECRUITMENT (6)
(
  'paradox-olivia',
  'AI recruiting assistant',
  'Olivia by Paradox automates recruiting tasks like screening, scheduling interviews, and answering candidate questions 24/7.',
  'https://paradox.ai',
  'HR & Recruitment',
  ARRAY['Recruiting', 'HR Automation', 'Chatbot'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.paradox.ai/favicon.ico'
),
(
  'hirevue',
  'AI video interviewing platform',
  'HireVue uses AI to analyze video interviews, assess candidates, and predict job performance. Helps companies scale hiring.',
  'https://hirevue.com',
  'HR & Recruitment',
  ARRAY['Recruiting', 'Video Interview', 'Assessment'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.hirevue.com/favicon.ico'
),
(
  'phenom',
  'AI talent experience platform',
  'Phenom uses AI to personalize candidate experiences, automate recruiting workflows, and predict hiring outcomes.',
  'https://phenom.com',
  'HR & Recruitment',
  ARRAY['Recruiting', 'HR Automation', 'Talent Management'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.phenom.com/favicon.ico'
),
(
  'eightfold-ai',
  'AI talent intelligence platform',
  'Eightfold uses AI to match candidates to jobs, identify internal talent, and predict career paths. Enterprise talent platform.',
  'https://eightfold.ai',
  'HR & Recruitment',
  ARRAY['Recruiting', 'Talent Management', 'Career Development'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://eightfold.ai/favicon.ico'
),
(
  'workday-peakon',
  'AI employee engagement platform',
  'Workday Peakon uses AI to analyze employee feedback, predict turnover, and provide actionable insights for HR teams.',
  'https://workday.com',
  'HR & Recruitment',
  ARRAY['Employee Engagement', 'Analytics', 'HR Automation'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.workday.com/favicon.ico'
),
(
  'lattice',
  'AI performance management',
  'Lattice uses AI to help managers set goals, conduct reviews, and develop talent. Modern performance management platform.',
  'https://lattice.com',
  'HR & Recruitment',
  ARRAY['Performance Management', 'Goal Setting', 'HR Automation'],
  ARRAY['Paid', 'Subscription'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://lattice.com/favicon.ico'
),

-- SALES TOOLS (6)
(
  'gong-ai',
  'AI revenue intelligence platform',
  'Gong records and analyzes sales calls to provide insights, coach reps, and predict deal outcomes. Built for sales teams.',
  'https://gong.io',
  'Sales Tools',
  ARRAY['Sales Analytics', 'Call Recording', 'Revenue Intelligence'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.gong.io/favicon.ico'
),
(
  'outreach',
  'AI sales engagement platform',
  'Outreach uses AI to optimize email sequences, predict best send times, and automate sales workflows. Modern sales platform.',
  'https://outreach.io',
  'Sales Tools',
  ARRAY['Sales Automation', 'Email', 'Lead Generation'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  true,
  'https://www.outreach.io/favicon.ico'
),
(
  'salesloft',
  'AI sales engagement',
  'SalesLoft uses AI to prioritize prospects, optimize outreach, and provide coaching insights. Complete sales engagement platform.',
  'https://salesloft.com',
  'Sales Tools',
  ARRAY['Sales Automation', 'Email', 'Pipeline Management'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://salesloft.com/favicon.ico'
),
(
  'clari',
  'AI revenue platform',
  'Clari uses AI to predict revenue, identify pipeline risks, and provide sales forecasting. Built for revenue operations teams.',
  'https://clari.com',
  'Sales Tools',
  ARRAY['Sales Forecasting', 'Revenue Intelligence', 'Pipeline Management'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.clari.com/favicon.ico'
),
(
  'chorus-ai',
  'Conversation intelligence for sales',
  'Chorus (now ZoomIQ) analyzes sales conversations to identify trends, coach reps, and improve win rates.',
  'https://chorus.ai',
  'Sales Tools',
  ARRAY['Sales Analytics', 'Call Recording', 'Coaching'],
  ARRAY['Enterprise', 'Paid'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://chorus.ai/favicon.ico'
),
(
  'apollo-io',
  'AI-powered sales intelligence',
  'Apollo uses AI to find prospects, enrich data, and automate outreach. Complete sales intelligence and engagement platform.',
  'https://apollo.io',
  'Sales Tools',
  ARRAY['Lead Generation', 'Prospecting', 'Sales Automation'],
  ARRAY['Freemium', 'Web App'],
  '70baaf04-9d57-49ea-8029-6ce7241697a3',
  true,
  false,
  'https://www.apollo.io/favicon.ico'
);

-- Update view counts to reasonable starting values
UPDATE public.products 
SET view_count = floor(random() * 1000 + 100)::int
WHERE view_count = 0;
